### ISSUE TITLE
Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by ralfstuckert** [Azure/k8s-deploy#161]
After upgrading from version v1.4 to v1.5 the following error occurs. The workflow itself was unchanged, rollback to v1.4 fixes the problem.

```
##[group***Run Azure/k8s-deploy@v1.5
with:
  namespace: xxx
  manifests: ./target/helm/output.yaml
  strategy: none
  route-method: service
  version-switch-buffer: 0
  traffic-split-method: pod
  baseline-and-canary-replicas: 0
  percentage: 0
  action: deploy
  force: false
  token: ***
env:
  KUBECONFIG: /home/runner/work/_temp/kubeconfig_1639042842062
##[endgroup***
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/Azure/k8s-deploy/v1.5/lib/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/Azure/k8s-deploy/v1.5/lib/run.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) ***
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/Azure/k8s-deploy/v1.5/lib/run.js' ***
***
```

**Comment by ralfstuckert** [comment]
Hi, thanks for your immediate help. Yes, I can confirm that it works with 1.5. I tried with **v**1.5 at first which was not found. So my final question: is 1.5 correct or will you change that to v1.5?

**Comment by davidgamero** [comment]
I'm glad it works, and yes I'll change it.
v1.5 should be live now. Thanks for your help 😄 

https://github.com/Azure/k8s-deploy/releases/tag/v1.5

**Comment by ralfstuckert** [comment]
yup, confirm v1.5 is working. Thanks for your support :-)
